export const databaseList = [
	{
		name: "staff",
		optionName: "Staff",
		keys: [
			"name_en",
			"name_tc",
			"staff_id",
			"account",
			"password",
			"email",
			"on_board_time",
			"status",
			"remarks",
			"division",
			"router_scy",
			"db_scy",
		],
		type: {
			name_en: {
				style: "input",
				require: true,
				validation: undefined,
			},
			name_tc: {
				style: "input",
				require: true,
				validation: undefined,
			},
			staff_id: {
				style: "input",
				require: true,
				validation: undefined,
			},
			account: {
				style: "input",
				require: true,
				validation: undefined,
			},
			password: {
				style: "input",
				require: true,
				validation: undefined,
			},
			email: {
				style: "input",
				require: true,
				validation: undefined,
			},
			on_board_time: {
				style: "date",
				require: true,
				validation: undefined,
			},
			status: {
				style: "select",
				options: "status",
				require: true,
				validation: undefined,
			},
			remarks: {
				style: "multi-input",
				require: false,
				validation: undefined,
			},
			division: {
				style: "select",
				options: "division",
				require: true,
				validation: undefined,
			},
			router_scy: {
				style: "select",
				options: "router_scy",
				require: true,
				validation: undefined,
			},
			db_scy: {
				style: "select",
				options: "db_scy",
				require: true,
				validation: undefined,
			},
		},
	},
	{
		name: "staff_group",
		optionName: "Staff Group",
		keys: [
			"name",
			"nickname",
			"established_date",
			"status",
			"staff_names",
			"remarks",
			"group_id",
		],
		type: {
			name: {
				style: "input",
				require: true,
				validation: undefined,
			},
			nickname: {
				style: "input",
				require: false,
				validation: undefined,
			},
			group_id: {
				style: "input",
				require: true,
				validation: undefined,
			},
			established_date: {
				style: "date",
				require: true,
				validation: undefined,
			},
			status: {
				style: "select",
				options: "status",
				require: true,
				validation: undefined,
			},
			remarks: {
				style: "multi-input",
				require: false,
				validation: undefined,
			},
			staff_names: {
				style: "multi-select",
				require: false,
				validation: undefined,
				options: "staff",
			},
		},
	},
	{
		name: "division",
		optionName: "Division",
		keys: ["name", "email", "status", "remarks", "division_id"],
		type: {
			name: {
				style: "input",
				require: true,
				validation: undefined,
			},
			email: {
				style: "input",
				require: false,
				validation: undefined,
			},
			division_id: {
				style: "input",
				require: true,
				validation: undefined,
			},
			status: {
				style: "select",
				options: "status",
				require: true,
				validation: undefined,
			},
			remarks: {
				style: "multi-input",
				require: false,
				validation: undefined,
			},
		},
	},
	{
		name: "partner",
		optionName: "Partner",
		keys: [
			"name_en",
			"name_local",
			"partner_id",
			"account",
			"password",
			"email",
			"job_title",
			"status",
			"remarks",
			"company",
			"router_scy",
			"db_scy",
			"partner_level",
		],
		type: {
			name_en: {
				style: "input",
				require: true,
				validation: undefined,
			},
			name_local: {
				style: "input",
				require: true,
				validation: undefined,
			},
			partner_id: {
				style: "input",
				require: true,
				validation: undefined,
			},
			account: {
				style: "input",
				require: true,
				validation: undefined,
			},
			password: {
				style: "input",
				require: true,
				validation: undefined,
			},
			email: {
				style: "input",
				require: true,
				validation: undefined,
			},
			job_title: {
				style: "input",
				require: true,
				validation: undefined,
			},
			status: {
				style: "select",
				options: "status",
				require: true,
				validation: undefined,
			},
			remarks: {
				style: "multi-input",
				require: false,
				validation: undefined,
			},
			company: {
				style: "select",
				options: "company",
				require: true,
				validation: undefined,
			},
			router_scy: {
				style: "select",
				options: "router_scy",
				require: true,
				validation: undefined,
			},
			db_scy: {
				style: "select",
				options: "db_scy",
				require: true,
				validation: undefined,
			},
			partner_level: {
				style: "select",
				options: "partner_level",
				require: true,
				validation: undefined,
			},
		},
	},
	{
		name: "partner_group",
		optionName: "Partner Group",
		keys: [
			"name",
			"nickname",
			"established_date",
			"status",
			"partner_names",
			"remarks",
			"partner_group_id",
		],
		type: {
			name: {
				style: "input",
				require: true,
				validation: undefined,
			},
			nickname: {
				style: "input",
				require: false,
				validation: undefined,
			},
			established_date: {
				style: "date",
				require: true,
				validation: undefined,
			},
			status: {
				style: "select",
				options: "status",
				require: true,
				validation: undefined,
			},
			remarks: {
				style: "multi-input",
				require: false,
				validation: undefined,
			},
			partner_group_id: {
				style: "input",
				require: true,
				validation: undefined,
			},
			partner_names: {
				style: "multi-select",
				options: "partner_names",
				require: false,
				validation: undefined,
			},
		},
	},
	{
		name: "company",
		optionName: "Company",
		keys: ["name", "nickname", "status", "remarks"],
		type: {
			name: {
				style: "input",
				require: true,
				validation: undefined,
			},
			nickname: {
				style: "input",
				require: false,
				validation: undefined,
			},
			status: {
				style: "select",
				options: "status",
				require: true,
				validation: undefined,
			},
			remarks: {
				style: "multi-input",
				require: false,
				validation: undefined,
			},
		},
	},
	{
		name: "firmware",
		optionName: "Firmware",
		keys: [
			"name",
			"status",
			"download_path_s",
			"download_path_g",
			"download_path_b",
			"remarks",
			"version",
			"major_sku",
			"resources_default_action",
		],
		type: {
			name: {
				style: "input",
				require: true,
				validation: undefined,
			},
			major_sku: {
				style: "select",
				options: "major_sku",
				require: true,
				validation: undefined,
			},
			status: {
				style: "select",
				options: "status",
				require: true,
				validation: undefined,
			},
			remarks: {
				style: "multi-input",
				require: false,
				validation: undefined,
			},
			download_path_s: {
				style: "input-file",
				file_type: "ppkg",
				require: true,
				validation: undefined,
			},
			resources_default_action: {
				style: "select",
				options: "resources_default_action",
				require: true,
				validation: undefined,
			},
			version: {
				style: "input",
				require: true,
				validation: undefined,
			},
			uploader: {
				style: "now-user",
				require: true,
				validation: undefined,
			},
			upload_date: {
				style: "now-date",
				require: true,
				validation: undefined,
			},
		},
	},
	{
		name: "software",
		optionName: "Software",
		keys: [
			"name",
			"status",
			"download_path_s",
			"download_path_g",
			"download_path_b",
			"remarks",
			"version",
			"owner",
			"resources_action",
		],
		type: {
			name: {
				style: "input",
				require: true,
				validation: undefined,
			},
			owner: {
				style: "multi-select",
				options: "owner",
				require: true,
				validation: undefined,
			},
			status: {
				style: "select",
				options: "status",
				require: true,
				validation: undefined,
			},
			remarks: {
				style: "multi-input",
				require: false,
				validation: undefined,
			},
			download_path_s: {
				style: "input-file",
				file_type: "tool",
				require: true,
				validation: undefined,
			},
			resources_default_action: {
				style: "select",
				options: "resources_default_action",
				require: true,
				validation: undefined,
			},
			version: {
				style: "input",
				require: true,
				validation: undefined,
			},
			uploader: {
				style: "now-user",
				require: true,
				validation: undefined,
			},
			upload_date: {
				style: "now-date",
				require: true,
				validation: undefined,
			},
		},
	},
	{
		name: "major_sku_type",
		optionName: "Major Sku Type",
		keys: ["name", "status", "photo", "remarks"],
		type: {
			name: {
				style: "input",
				require: true,
				validation: undefined,
			},
			photo: {
				style: "input-file",
				file_type: "photo",
				require: false,
				validation: undefined,
			},
			status: {
				style: "select",
				options: "status",
				require: true,
				validation: undefined,
			},
			remarks: {
				style: "multi-input",
				require: false,
				validation: undefined,
			},
		},
	},
	{
		name: "major_sku",
		optionName: "Major Sku",
		keys: [
			"name",
			"status",
			"photo",
			"major_sku_type",
			"owner",
			"documents",
			"remarks",
		],
		type: {
			name: {
				style: "input",
				require: true,
				validation: undefined,
			},
			photo: {
				style: "input-file",
				file_type: "photo",
				require: false,
				validation: undefined,
			},
			status: {
				style: "select",
				options: "status",
				require: true,
				validation: undefined,
			},
			remarks: {
				style: "multi-input",
				require: false,
				validation: undefined,
			},
			major_sku_type: {
				style: "select",
				options: "major_sku_type",
				require: true,
				validation: undefined,
			},
			owner: {
				style: "multi-select",
				options: "owner",
				require: true,
				validation: undefined,
			},
			documents: {
				style: "multi-select",
				options: "document",
				require: true,
				validation: undefined,
			},
		},
	},
	{
		name: "document_type",
		optionName: "Document Type",
		keys: ["name", "status", "remarks"],
		type: {
			name: {
				style: "input",
				require: true,
				validation: undefined,
			},
			status: {
				style: "select",
				options: "status",
				require: true,
				validation: undefined,
			},
			remarks: {
				style: "multi-input",
				require: false,
				validation: undefined,
			},
		},
	},
	{
		name: "document",
		optionName: "Document",
		keys: [
			"name",
			"file_name",
			"nickname",
			"status",
			"download_path_s",
			"download_path_g",
			"download_path_b",
			"remarks",
			"version",
			"owner",
			"resources_default_action",
		],
		type: {
			name: {
				style: "input",
				require: true,
				validation: undefined,
			},
			file_name: {
				style: "input",
				require: true,
				validation: undefined,
			},
			nickname: {
				style: "input",
				require: false,
				validation: undefined,
			},
			status: {
				style: "select",
				options: "status",
				require: true,
				validation: undefined,
			},
			remarks: {
				style: "multi-input",
				require: false,
				validation: undefined,
			},
			download_path_s: {
				style: "input-file",
				file_type: "tool",
				require: true,
				validation: undefined,
			},
			owner: {
				style: "multi-select",
				options: "owner",
				require: true,
				validation: undefined,
			},
			resources_default_action: {
				style: "select",
				options: "resources_default_action",
				require: true,
				validation: undefined,
			},
			version: {
				style: "input",
				require: true,
				validation: undefined,
			},
			uploader: {
				style: "now-user",
				require: true,
				validation: undefined,
			},
			upload_date: {
				style: "now-date",
				require: true,
				validation: undefined,
			},
			language_ver: {
				style: "input",
				require: true,
				validation: undefined,
			},
			document_language: {
				style: "select",
				options: "document_language",
				require: true,
				validation: undefined,
			},
		},
	},
	{
		name: "partner_level",
		optionName: "Partner Level",
		keys: [
			"name",
			"status",
			"special_documents",
			"special_firmware",
			"special_software",
			"owner",
		],
		type: {
			name: {
				style: "input",
				require: true,
				validation: undefined,
			},
			status: {
				style: "select",
				options: "status",
				require: true,
				validation: undefined,
			},
			owner: {
				style: "multi-select",
				options: "owner",
				require: true,
				validation: undefined,
			},
		},
		special_type: {
			special_documents: {
				require: false,
				form: {
					resources_default_action: {
						style: "select",
						options: "resources_default_action",
						require: true,
						validation: undefined,
					},
					target: {
						style: "select",
						options: "document",
						require: true,
						validation: undefined,
					},
				},
			},
			special_software: {
				require: false,
				form: {
					resources_default_action: {
						style: "select",
						options: "resources_default_action",
						require: true,
						validation: undefined,
					},
					target: {
						style: "select",
						options: "document",
						require: true,
						validation: undefined,
					},
				},
			},
			special_firmware: {
				require: false,
				form: {
					resources_default_action: {
						style: "select",
						options: "resources_default_action",
						require: true,
						validation: undefined,
					},
					target: {
						style: "select",
						options: "document",
						require: true,
						validation: undefined,
					},
				},
			},
		},
	},
	{
		name: "router_security",
		optionName: "Router Security",
		keys: ["name", "status", "router_ctrl"],
		type: {
			name: {
				style: "input",
				require: true,
				validation: undefined,
			},
			status: {
				style: "select",
				options: "status",
				require: true,
				validation: undefined,
			},
		},
		special_type: {
			router_ctrl: {
				require: false,
				form: {
					router_path: {
						style: "select",
						options: "router_options",
						require: true,
						validation: undefined,
					},
					database_function_control: {
						style: "multi-select",
						options: "database_function_control",
						require: true,
						validation: undefined,
					},
				},
			},
		},
	},
	{
		name: "database_security",
		optionName: "Database Security",
		keys: ["name", "status", "db_ctrl"],
		type: {
			name: {
				style: "input",
				require: true,
				validation: undefined,
			},
			status: {
				style: "select",
				options: "status",
				require: true,
				validation: undefined,
			},
			db_ctrl: {
				style: "select",
				options: "db_ctrl",
				require: true,
				validation: undefined,
			},
		},
	},
	{
		name: "db_ctrl",
		optionName: "DataBase Sensitive Control",
		keys: [
			"filter_dependence",
			"filter_target",
			"status",
			"db_path",
			"sensitive_field",
		],
		type: {
			name: {
				style: "input",
				require: true,
				validation: undefined,
			},
			status: {
				style: "select",
				options: "status",
				require: true,
				validation: undefined,
			},
			filter_dependence: {
				style: "select",
				options: "database_Security_Filter_Dependence",
				require: true,
				validation: undefined,
			},
			db_path: {
				style: "select",
				options: "database_options",
				require: true,
				validation: undefined,
			},
			filter_target: {
				style: "input",
				require: true,
				validation: undefined,
			},
		},
	},
];
