export const databaseList = [
	{
		name: "staff",
		optionName: "Staff",
		keys: [
			"name",
			"tc_name",
			"staff_id",
			"account",
			"password",
			"email",
			"on_board_time",
			"status",
			"remarks",
			"division",
			"router_scy",
			"db_scy",
		],
		optional_keys: ["remarks"],
	},
	{
		name: "staff_group",
		optionName: "Staff Group",
		keys: [
			"name",
			"short_name",
			"established_date",
			"status",
			"staff_names",
			"remarks",
		],
		optional_keys: ["short_name", "remarks"],
	},
	{
		name: "division",
		optionName: "Division",
		keys: ["name", "email", "status", "remarks"],
		optional_keys: ["email", "remarks"],
	},
	{
		name: "partner",
		optionName: "Partner",
		keys: [
			"name",
			"tc_name",
			"partner_id",
			"account",
			"password",
			"email",
			"job_title",
			"status",
			"remarks",
			"company",
			"router_scy",
			"db_scy",
			"partner_level",
		],
		optional_keys: ["tc_name", "remarks"],
	},
	{
		name: "partner_group",
		optionName: "Partner Group",
		keys: [
			"name",
			"short_name",
			"established_date",
			"status",
			"partner_names",
			"remarks",
		],
		optional_keys: ["short_name", "remarks"],
	},
	{
		name: "company",
		optionName: "Company",
		keys: ["name", "status", "remarks"],
		optional_keys: ["remarks"],
	},
	{
		name: "firmware",
		optionName: "Firmware",
		keys: [
			"name",
			"status",
			"download_path_s",
			"download_path_g",
			"download_path_b",
			"remarks",
			"version",
			"major_sku",
			"resources_action",
		],
		optional_keys: ["remarks", "download_path_g", "download_path_b"],
	},
	{
		name: "software",
		optionName: "Software",
		keys: [
			"name",
			"status",
			"download_path_s",
			"download_path_g",
			"download_path_b",
			"remarks",
			"version",
			"owner",
			"resources_action",
		],
		optional_keys: ["remarks", "download_path_s", "download_path_b"],
	},
	{
		name: "major_sku_type",
		optionName: "Major Sku Type",
		keys: ["name", "status", "photo", "remarks"],
		optional_keys: ["remarks"],
	},
	{
		name: "major_sku",
		optionName: "Major Sku",
		keys: ["name", "status", "photo", "major_sku_type", "owner", "documents"],
		optional_keys: ["remarks"],
	},
	{
		name: "document_type",
		optionName: "Document Type",
		keys: ["name", "status", "remarks"],
		optional_keys: ["remarks"],
	},
	{
		name: "document",
		optionName: "Document",
		keys: [
			"name",
			"document_name",
			"status",
			"download_path_s",
			"download_path_g",
			"download_path_b",
			"remarks",
			"version",
			"owner",
			"resources_action",
		],
		optional_keys: ["remarks", "download_path_g", "download_path_b"],
	},
	{
		name: "partner_level",
		optionName: "Partner Level",
		keys: [
			"name",
			"status",
			"special_documents",
			"special_firmware",
			"special_software",
			"owner",
		],
		optional_keys: [],
	},
	{
		name: "router_security",
		optionName: "Router Security",
		keys: ["name", "status", "router_ctrl"],
		optional_keys: [],
	},
	{
		name: "database_security",
		optionName: "Database Security",
		keys: ["name", "status", "db_ctrl"],
		optional_keys: [],
	},
];
