export const routers_partner = [
	{
		name: "Partner Portal Introduce",
		path: "/",
		main_path: "",
		tree_view_name: "",
		component: "../views/PartnerPortal/Introduce/index.vue",
		belong: "",
		level: 0,
	},
	{
		name: "Partner Portal Login",
		path: "/login",
		main_path: "/partnerPortal",
		tree_view_name: "",
		component: "../views/PartnerPortal/Login/index.vue",
		belong: "",
		level: 0,
	},
	{
		name: "Major SKU List",
		path: "/majorSku",
		main_path: "/partnerPortal",
		tree_view_name: "routers_tree_view.majorSKU",
		component: "../views/PartnerPortal/MajorSKU/index.vue",
		belong: "",
		level: 1,
	},
	{
		name: "Major SKU",
		path: "/:id",
		main_path: "/partnerPortal/majorSku",
		tree_view_name: "",
		component: "../views/PartnerPortal/MajorSKU/_id.vue",
		belong: "",
		level: 0,
	},
];

export const routers_backStage = [
	// 總控平台
	{
		name: "Cino System Control",
		path: "/backStage",
		main_path: "",
		tree_view_name: "",
		component: "../views/BackStage/index.vue",
		belong: "",
		level: 0,
	},
	{
		name: "Cino System Control Login",
		path: "/login",
		main_path: "/backStage",
		tree_view_name: "",
		component: "../views/BackStage/Login/index.vue",
		belong: "",
		level: 0,
	},
];

export const routers_partner_portal_backStage = [
	// Partner Portal BackStage 首頁
	{
		name: "Partner Portal BackStage Introduce",
		path: "/introduce",
		main_path: "/backStage/partnerPortal",
		tree_view_name: "",
		component: "../views/BackStage/PartnerPortal/Introduce.vue",
		belong: "",
		level: 0,
	},
	// Account Management
	{
		name: "Account Management",
		path: "",
		main_path: "",
		tree_view_name: "routers_tree_view.accountManagement",
		component: "",
		belong: "",
		level: 1,
	},
	{
		name: "Staff",
		path: "",
		main_path: "",
		tree_view_name: "routers_tree_view.staff",
		component: "",
		belong: "routers_tree_view.accountManagement",
		level: 2,
	},
	{
		name: "Staff List",
		path: "/staff",
		main_path: "/backStage/partnerPortal",
		tree_view_name: "routers_tree_view.staffList",
		component: "../views/BackStage/PartnerPortal/Staff.vue",
		belong: "routers_tree_view.staff",
		level: 3,
	},
	{
		name: "Division List",
		path: "/division",
		main_path: "/backStage/partnerPortal",
		tree_view_name: "routers_tree_view.divisionList",
		component: "../views/BackStage/PartnerPortal/Division.vue",
		belong: "routers_tree_view.staff",
		level: 3,
	},
	{
		name: "Staff Group",
		path: "/staffGroup",
		main_path: "/backStage/partnerPortal",
		tree_view_name: "routers_tree_view.staffGroup",
		component: "../views/BackStage/PartnerPortal/StaffGroup.vue",
		belong: "routers_tree_view.staff",
		level: 3,
	},
	{
		name: "Partner",
		path: "",
		main_path: "",
		tree_view_name: "routers_tree_view.partner",
		component: "",
		belong: "routers_tree_view.accountManagement",
		level: 2,
	},
	{
		name: "Partner List",
		path: "/partner",
		main_path: "/backStage/partnerPortal",
		tree_view_name: "routers_tree_view.partnerList",
		component: "../views/BackStage/PartnerPortal/Partner.vue",
		belong: "routers_tree_view.partner",
		level: 3,
	},
	{
		name: "Partner Level",
		path: "/partnerLevel",
		main_path: "/backStage/partnerPortal",
		tree_view_name: "routers_tree_view.partnerLevel",
		component: "../views/BackStage/PartnerPortal/PartnerLevel.vue",
		belong: "routers_tree_view.partner",
		level: 3,
	},
	{
		name: "Company List",
		path: "/company",
		main_path: "/backStage/partnerPortal",
		tree_view_name: "routers_tree_view.companyList",
		component: "../views/BackStage/PartnerPortal/Company.vue",
		belong: "routers_tree_view.partner",
		level: 3,
	},
	{
		name: "Partner Group",
		path: "/partnerGroup",
		main_path: "/backStage/partnerPortal",
		tree_view_name: "routers_tree_view.partnerGroup",
		component: "../views/BackStage/PartnerPortal/PartnerGroup.vue",
		belong: "routers_tree_view.partner",
		level: 3,
	},
	{
		name: "Security",
		path: "",
		main_path: "",
		tree_view_name: "routers_tree_view.security",
		component: "",
		belong: "routers_tree_view.accountManagement",
		level: 2,
	},
	{
		name: "Router Security",
		path: "/routerSecurity",
		main_path: "/backStage/partnerPortal",
		tree_view_name: "routers_tree_view.routerSecurity",
		component: "../views/BackStage/PartnerPortal/RouterSecurity.vue",
		belong: "routers_tree_view.security",
		level: 3,
	},
	{
		name: "Database Security",
		path: "/databaseSecurity",
		main_path: "/backStage/partnerPortal",
		tree_view_name: "routers_tree_view.databaseSecurity",
		component: "../views/BackStage/PartnerPortal/DatabaseSecurity.vue",
		belong: "routers_tree_view.security",
		level: 3,
	},
	// Product Management
	{
		name: "Product Management",
		path: "",
		main_path: "",
		tree_view_name: "routers_tree_view.productManagement",
		component: "",
		belong: "",
		level: 1,
	},
	{
		name: "Major Sku List",
		path: "/majorSku",
		main_path: "/backStage/partnerPortal",
		tree_view_name: "routers_tree_view.majorSkuList",
		component: "../views/BackStage/PartnerPortal/MajorSku.vue",
		belong: "routers_tree_view.productManagement",
		level: 2,
	},
	{
		name: "Major Sku Type",
		path: "/majorSkuType",
		main_path: "/backStage/partnerPortal",
		tree_view_name: "routers_tree_view.majorSkuType",
		component: "../views/BackStage/PartnerPortal/MajorSkuType.vue",
		belong: "routers_tree_view.productManagement",
		level: 2,
	},
	// Resources Management
	{
		name: "Resources Management",
		path: "",
		main_path: "",
		tree_view_name: "routers_tree_view.resourcesManagement",
		component: "",
		belong: "",
		level: 1,
	},
	{
		name: "Document",
		path: "",
		main_path: "",
		tree_view_name: "routers_tree_view.document",
		component: "",
		belong: "routers_tree_view.resourcesManagement",
		level: 2,
	},
	{
		name: "Document List",
		path: "/document",
		main_path: "/backStage/partnerPortal",
		tree_view_name: "routers_tree_view.documentList",
		component: "../views/BackStage/PartnerPortal/Document.vue",
		belong: "routers_tree_view.document",
		level: 3,
	},
	{
		name: "Document Type",
		path: "/documentType",
		main_path: "/backStage/partnerPortal",
		tree_view_name: "routers_tree_view.documentType",
		component: "../views/BackStage/PartnerPortal/DocumentType.vue",
		belong: "routers_tree_view.document",
		level: 3,
	},
	{
		name: "Firmware List",
		path: "/firmware",
		main_path: "/backStage/partnerPortal",
		tree_view_name: "routers_tree_view.firmwareList",
		component: "../views/BackStage/PartnerPortal/Firmware.vue",
		belong: "routers_tree_view.resourcesManagement",
		level: 2,
	},
	{
		name: "Software List",
		path: "/software",
		main_path: "/backStage/partnerPortal",
		tree_view_name: "routers_tree_view.softwareList",
		component: "../views/BackStage/PartnerPortal/Software.vue",
		belong: "routers_tree_view.resourcesManagement",
		level: 2,
	},
	// Powertool3 Management
	{
		name: "Powertool3 Management",
		path: "",
		main_path: "",
		tree_view_name: "routers_tree_view.powertool3Management",
		component: "",
		belong: "",
		level: 1,
	},
	{
		name: "Powertool3 Parameter",
		path: "/parameterDatabase",
		main_path: "/backStage/partnerPortal",
		tree_view_name: "routers_tree_view.powertool3Parameter",
		component: "../views/BackStage/PowerTool/Parameter.vue",
		belong: "routers_tree_view.powertool3Management",
		level: 2,
	},
	// Action Log
	{
		name: "Action Log",
		path: "/actionLog",
		main_path: "/backStage/partnerPortal",
		tree_view_name: "routers_tree_view.actionLog",
		component: "../views/BackStage/PartnerPortal/ActionLog.vue",
		belong: "",
		level: 1,
	},
];
